### ISSUE TITLE
Pass all `read` calls through utf-8 filter

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#230]
### Motivation
- [x] **Device names with apostrophes cause invalid byte sequence in US-ASCII (ArgumentError)** #74  
- [x] **Handle UTF-8 characters in output of `instruments`** #219
- [ ] All the other places where we call `read` on the output of a shell command.

**Comment by jmoody** [comment]
mostly fixed.
