### ISSUE TITLE
`simctl install` on iPad Simulators installs an app that is not recognized by Springboard or simctl

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#435]
### Reproduce

```
1. Change the spec/integration/core_simulator_spec.rb simulator to be an iPad
2. $ be rspec spec/integration/core_simulator_spec.rb:95
```

### Expected

To fail 2 times and launch the app on the iPad on the third try.

### Found

The app is installed, but not recognized by Springboard or simctl.

### TODO

- [x]  Confirm `simctl get_app_container` does not return a directory after `simctl install`.
- [x]  ~~File a bug with Apple~~  Will not bother
- [x] Figure out how to work around.

### Notes 

The problem is that the simulator is not _ready for the app to be installed_.  If you want an unreasonable amount of time (e.g. 30 seconds _after_ the simulator stabilizes), the install will always work.  The rewrite of the sim-stable algorithm in #455 takes iPads into account.
